# Generated by Django 4.2.5 on 2023-09-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='user',
        ),
    ]
