# Generated by Django 4.2.5 on 2023-10-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('network', models.TextField()),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
