# Generated by Django 4.2.5 on 2023-10-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='shows',
        ),
    ]
